Interest.Presentation/Models/ComputationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Interest.Presentation.Models
{
    public class ComputationViewModel
    {
        public int Id { get; set; }
        public decimal Value { get; set; }
        public decimal InterestRate { get; set; }
        public decimal FutureValue { get; set; }
        public int Year { get; set; }
    }
}

Interest.Presentation/Models/ErrorViewModel.cs
using System;

namespace Interest.Presentation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Interest.Presentation/Models/RequestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Interest.Presentation.Models
{
    public class RequestViewModel
    {
        public int Id { get; set; }
        public decimal Value { get; set; }
        public IEnumerable<ComputationViewModel> Computations { get; set; }

    }

    public class ComputationViewModel
    {
        public int Id { get; set; }
        public decimal Value { get; set; }
        public decimal InterestRate { get; set; }
        public decimal FutureValue { get; set; }
        public int Year { get; set; }
    }
}

Interest.Presentation/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Interest.Presentation.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Interest.Presentation/Controllers/HomeController.cs
using Interest.Presentation.Models;
using Interest.Presentation.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace Interest.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly IRequestService _requestService;
        public HomeController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        public async Task<IActionResult> Index(int id = 0, bool isDeleted = false)
        {
            ViewBag.Id = id;
            ViewBag.isDeleted = isDeleted;

            var requests = await _requestService.GetRequestList();
            return View(requests.OrderByDescending(r => r.Id));
        }
    }
}

Interest.Presentation/Controllers/RequestController.cs
using Interest.Presentation.Models;
using Interest.Presentation.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Interest.Presentation.Controllers
{
    public class RequestController : Controller
    {

        private readonly IRequestService _requestService;
        public RequestController(IRequestService requestService)
        {
            _requestService = requestService;
        }

        public async Task<IActionResult> AddRequest()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddRequest(decimal value)
        {
            try
            {
                var requestId = await _requestService.AddRequest(value);

                return RedirectToAction("ViewRequest", new { id = requestId, isUpdated = true });
            }
            catch (Exception)
            {

                return RedirectToAction("Index", "Error");
            }
        }

        public async Task<IActionResult> EditRequest(int id)
        {
            try
            {
                var request = await _requestService.GetRequest(id);
                return View(request);
            }
            catch (Exception)
            {

                return RedirectToAction("Index", "Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> EditRequest([FromForm]RequestViewModel viewModel)
        {
            try
            {
                if (viewModel.IsComputed)
                {
                    var requestId = await _requestService.UpdateRequest(viewModel);
                    return RedirectToAction("ViewRequest", new { id = requestId, isUpdated = true });
                }

                var computations = await _requestService.GetRequestComputaions(viewModel.Value);
                viewModel.Computations = computations;

                viewModel.IsComputed = true;
                return View(viewModel);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public async Task<IActionResult> ViewRequest(int id, bool isUpdated = false)
        {
            try
            {
                var request = await _requestService.GetRequest(id);
                request.IsUpdated = isUpdated;
                return View(request);
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Error");
            }
        }

        public async Task<IActionResult> DeleteRequest(int id)
        {
            try
            {
                var requestId = await _requestService.DeleteRequest(id);
                return RedirectToAction("Index", "Home", new { id = 1, isDeleted = true });
            }
            catch (Exception)
            {
                return RedirectToAction("Index", "Error");
            }
        }
    }
}

Interest.Presentation/Views/Home/Index.cshtml
@model IEnumerable<RequestViewModel>

@{
    ViewData["Title"] = "Home Page";
}

@if (ViewBag.Id > 0 && ViewBag.isDeleted)
{
    <div class="alert alert-danger" role="alert">
        Request @ViewBag.Id has been deleted
    </div>
}

@foreach (var request in Model)
{
    <h2>Interest Request: @request.Id</h2>
    <a href="/Request/EditRequest/@request.Id" class="btn btn-primary">Edit request</a>
    <br />
    <a href="/Request/DeleteRequest/@request.Id" class="btn btn-danger">Delete request</a>
    <br />
    <span>Entered value: @request.Value</span>
    <h4>Computations</h4>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Year</th>
                <th scope="col">Value</th>
                <th scope="col">Interest Rate</th>
                <th scope="col">Future Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var computation in request.Computations)
            {
                <tr>
                    <th scope="row">@computation.Year</th>
                    <td>@computation.Value</td>
                    <td>@computation.InterestRate</td>
                    <td>@computation.FutureValue</td>
                </tr>
            }
        </tbody>
    </table>
}

Interest.Presentation/Views/Request/AddRequest.cshtml
@{
    ViewData["Title"] = "Add Request";
}

<h2>Add Request</h2>
<br />
<br />

<form action="AddRequest" method="post">
    <div class="form-group">
        <label for="value">Enter Value</label>
        <input name="value" type="number" step="0.01" class="form-control" id="interestValue"placeholder="Enter Value">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Interest.Presentation/Views/Request/EditRequest.cshtml
@model Interest.Presentation.Models.RequestViewModel

@{
    ViewData["Title"] = "EditRequest";
}

<h1>EDIT REQUEST</h1>
<hr />
<h2>Request no: @Model.Id</h2>
<form asp-action="EditRequest" method="post">
    <div class="row">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Value" class="control-label"></label>
                <input asp-for="Value" type="number" step="0.01" class="form-control" />
                <span asp-validation-for="Value" class="text-danger"></span>
            </div>
            <input name="Id" value="@Model.Id" hidden />

            <input name="IsComputed" value="@Model.IsComputed.ToString()" hidden />
            <div class="form-group">
                <input type="submit" value="Compute" class="btn btn-secondary w-100" />
            </div>
        </div>
    </div>

    <h4>Computations</h4>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Year</th>
                <th scope="col">Value</th>
                <th scope="col">Interest Rate</th>
                <th scope="col">Future Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var computation in Model.Computations)
            {
                <tr>
                    <th scope="row">@computation.Year</th>
                    <td>@computation.Value</td>
                    <td>@computation.InterestRate</td>
                    <td>@computation.FutureValue</td>
                </tr>
            }
        </tbody>
    </table>
    @if (Model.IsComputed)
    {
        <input type="submit" value="Save" class="btn btn-primary w-100" />
    }
    else
    {
        <input type="submit" value="Save" class="btn btn-secondary w-100" disabled/>
    }
</form>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Interest.Presentation/Views/Request/ViewRequest.cshtml
@model Interest.Presentation.Models.RequestViewModel

@{
    ViewData["Title"] = "View Request";
}
@if (Model.IsUpdated)
{
    <div class="alert alert-success" role="alert">
        Successfully save request
    </div>
}
<h1>View REQUEST</h1>
<hr />
<h2>Request no: @Model.Id</h2>
<a href="/Request/EditRequest/@Model.Id" class="btn btn-primary">Edit request</a>
<h4>Entered value @Model.Value</h4>
<h4>Computations</h4>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Year</th>
            <th scope="col">Value</th>
            <th scope="col">Interest Rate</th>
            <th scope="col">Future Value</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var computation in Model.Computations)
        {
            <tr>
                <th scope="row">@computation.Year</th>
                <td>@computation.Value</td>
                <td>@computation.InterestRate</td>
                <td>@computation.FutureValue</td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Home" asp-action="Index">Back to List</a>
</div>

Interest.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Interest APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Interest APP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="AddRequest">Add Request</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>